plugins {
    id 'java-library'
    id 'application'
    id 'maven-publish'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    api("uk.co.electronstudio.jaylib:jaylib:6.0.1-0")
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'Main'
}

java {
    withSourcesJar()
}

publishing {
    publications {
        library(MavenPublication) {
            from components.java
        }
    }
}